//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public byte id { get; set; }
        public string materia1 { get; set; }
        public string dia_semana { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public byte maestro_id { get; set; }
    }
}
