//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        public byte id { get; set; }
        public string tarea1 { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<byte> materia_id { get; set; }
    }
}
