//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public byte id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario1 { get; set; }
        public string password { get; set; }
        public string matricula { get; set; }
        public Nullable<int> estatus { get; set; }
    }
}
